### ISSUE TITLE
logging doesn't max out

### ISSUE THREAD

**Issue by christrotter** [christrotter/rgb-matrix-api#4]
Add something like this to the docker-compose file.  Need this regardless - it's a long-running service, and stdout is stdout, dump it into a log store or discard.

```
services:
    service_name:        
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
```
